--liquibase formatted sql
--changeset nastavnik:002-create-region
CREATE TABLE region (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        INTEGER NOT NULL,
    name        VARCHAR(500) NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT  uk_region_code UNIQUE (code)
);