--liquibase formatted sql
--changeset nastavnik:003-create-msu
CREATE TABLE msu (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id   BIGINT NOT NULL,
    code        INTEGER NOT NULL,
    name        VARCHAR(500) NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT  fk_msu_region FOREIGN KEY (region_id) REFERENCES region (id),
    CONSTRAINT  uk_msu_region_code UNIQUE (region_id, code),
    CONSTRAINT  uk_msu_id_region UNIQUE (id, region_id)
);