--liquibase formatted sql
--changeset nastavnik:004-create-educational-organization
CREATE TABLE educational_organization (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msu_id      BIGINT NOT NULL,
    code        INTEGER NOT NULL,
    name        VARCHAR(500) NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT  fk_oo_msu FOREIGN KEY (msu_id) REFERENCES msu (id),
    CONSTRAINT  uk_oo_msu_code UNIQUE (msu_id, code),
    CONSTRAINT  uk_oo_id_msu UNIQUE (id, msu_id)
);