--liquibase formatted sql
--changeset nastavnik:005-create-role
CREATE TABLE role (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,

    CONSTRAINT  uk_role_code UNIQUE (code)
);