--liquibase formatted sql
--changeset nastavnik:006-create-users
CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               CITEXT NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    middle_name         VARCHAR(100),
    birth_date          DATE NOT NULL,
    region_id           BIGINT NOT NULL,
    msu_id              BIGINT,
    educational_org_id  BIGINT,
    role_id             SMALLINT NOT NULL,
    account_status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    is_blocked          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT          uk_users_id_msu UNIQUE (id, msu_id),
    CONSTRAINT          uk_users_email UNIQUE (email),
    CONSTRAINT          chk_users_email_length CHECK (length(email) <= 250),
    CONSTRAINT          fk_users_region FOREIGN KEY (region_id) REFERENCES region (id),
    CONSTRAINT          fk_users_msu_region FOREIGN KEY (msu_id, region_id) REFERENCES msu (id, region_id),
    CONSTRAINT          fk_users_oo_msu FOREIGN KEY (educational_org_id, msu_id) REFERENCES educational_organization (id, msu_id),
    CONSTRAINT          fk_users_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT          chk_users_account_status CHECK (account_status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);