--liquibase formatted sql
--changeset nastavnik:010-create-profile-field-option
CREATE TABLE profile_field_option (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_field_id  BIGINT NOT NULL,
    value             VARCHAR(255) NOT NULL,
    label             VARCHAR(255) NOT NULL,
    active            BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT        fk_profile_field_option_field FOREIGN KEY (profile_field_id) REFERENCES profile_field (id) ON DELETE CASCADE,
    CONSTRAINT        uk_profile_field_option_value UNIQUE (profile_field_id, value),
    CONSTRAINT        uk_profile_field_option_id_field UNIQUE (id, profile_field_id)
);