--liquibase formatted sql
--changeset nastavnik:011-create-profile-value
CREATE TABLE profile_value (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    profile_field_id  BIGINT NOT NULL,
    value_text        TEXT,
    value_number      NUMERIC,
    value_boolean     BOOLEAN,
    value_date        DATE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT        fk_profile_value_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT        fk_profile_value_field FOREIGN KEY (profile_field_id) REFERENCES profile_field (id),
    CONSTRAINT        uk_profile_value_user_field UNIQUE (user_id, profile_field_id),
    CONSTRAINT        uk_profile_value_id_field UNIQUE (id, profile_field_id),
    CONSTRAINT        chk_profile_value_single_value CHECK (num_nonnulls(value_text, value_number, value_boolean, value_date) <= 1)
);