--liquibase formatted sql
--changeset nastavnik:013-create-academic-year
CREATE TABLE academic_year (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT  uk_academic_year_name UNIQUE (name),
    CONSTRAINT  chk_academic_year_dates CHECK (start_date < end_date)
);