--liquibase formatted sql
--changeset nastavnik:014-create-mentor-participation
CREATE TABLE mentor_participation (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_id         BIGINT NOT NULL,
    academic_year_id  BIGINT NOT NULL,
    participated      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT        fk_mentor_participation_mentor FOREIGN KEY (mentor_id) REFERENCES users (id),
    CONSTRAINT        fk_mentor_participation_year FOREIGN KEY (academic_year_id) REFERENCES academic_year (id),
    CONSTRAINT        uk_mentor_participation UNIQUE (mentor_id, academic_year_id)
);