--liquibase formatted sql
--changeset nastavnik:015-create-mentorship
CREATE TABLE mentorship (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_id           BIGINT NOT NULL,
    mentee_id           BIGINT NOT NULL,
    created_by          BIGINT NOT NULL,
    academic_year_id    BIGINT NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    msu_id              BIGINT NOT NULL,
    started_at          TIMESTAMPTZ,
    ended_at            TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT          fk_mentorship_msu FOREIGN KEY (msu_id) REFERENCES msu (id),
    CONSTRAINT          fk_mentorship_mentor_msu FOREIGN KEY (mentor_id, msu_id) REFERENCES users (id, msu_id),
    CONSTRAINT          fk_mentorship_mentee_msu FOREIGN KEY (mentee_id, msu_id) REFERENCES users (id, msu_id),
    CONSTRAINT          fk_mentorship_created_by_msu FOREIGN KEY (created_by, msu_id) REFERENCES users (id, msu_id),
    CONSTRAINT          uk_mentorship_id_msu UNIQUE (id, msu_id),
    CONSTRAINT          fk_mentorship_academic_year FOREIGN KEY (academic_year_id) REFERENCES academic_year (id),
    CONSTRAINT          chk_mentorship_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'ENDED', 'EXPIRED')),
    CONSTRAINT          chk_mentorship_status_dates
        CHECK (
            (
                status IN ('PENDING', 'REJECTED', 'EXPIRED')
                AND started_at IS NULL
                AND ended_at IS NULL
            )
            OR
            (
                status = 'ACCEPTED'
                AND started_at IS NOT NULL
                AND ended_at IS NULL
            )
            OR
            (
                status = 'ENDED'
                AND started_at IS NOT NULL
                AND ended_at IS NOT NULL
                AND started_at <= ended_at
            )
        ),

    CONSTRAINT          chk_mentorship_different_users CHECK (mentor_id <> mentee_id)
);