package org.donriro.nastavnik.config.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    EMAIL_ALREADY_EXISTS,
    MSU_NOT_FOUND,
    EDUCATIONAL_ORGANIZATION_NOT_FOUND,
    ROLE_NOT_FOUND,
    ADMINISTRATOR_ALREADY_EXISTS,
    INVALID_REGISTRATION_SCOPE,
    INVALID_REGISTRATION_ROLE,
    REGION_NOT_INITIALIZED,
    REGION_ALREADY_INITIALIZED,
    REGION_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_REFRESH_TOKEN
}
